// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7ndhjZUeNmQQRCil3fQVtpqD6L20QV4',
    appId: '1:342790448321:web:ce4fb77d863c4ca7da2040',
    messagingSenderId: '342790448321',
    projectId: 'jaljayo',
    authDomain: 'jaljayo.firebaseapp.com',
    storageBucket: 'jaljayo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-T-_rey-9bNL1XGDi1WPkhZ8gU4tdd0',
    appId: '1:342790448321:android:0eff7e3e21e8b9e8da2040',
    messagingSenderId: '342790448321',
    projectId: 'jaljayo',
    storageBucket: 'jaljayo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6O0gxM5rc3pSL2-So5oFbS_Ql8PJhJg',
    appId: '1:342790448321:ios:bd61e4b51b68ab6bda2040',
    messagingSenderId: '342790448321',
    projectId: 'jaljayo',
    storageBucket: 'jaljayo.appspot.com',
    iosBundleId: 'com.example.jaljayo',
  );
}
